title = "Social Interaction Lab"
baseURL = "https://social-interaction-lab.github.io/"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6           # this is set low for demonstrating with dummy content.
googleAnalytics = ""
enableRobotsTXT = true



[languages]
  [languages.en]
    title = "Social Interaction Lab"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

  [languages.cn]
    title = "社会互动实验室"
    weight = 2
    contentDir = "content/cn"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"



[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  background_color_class = "bg-black"
  recent_posts_number = 2
  custom_css = ["custom.css"]

#########################
######## hide ###########
#########################
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"


#[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/GoHugoIO"

#[[menu.en]]
#    name = "Home"
#    url = "/"
#    weight = 1

#[[menu.cn]]
#    name = "中文首页"
#    url = "/cn/"
#    weight = 1